name: PIPELINE

on:
  push:
    branches:
      - develop
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

      
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: ./backend/src
      run: npm install
    - name: Run integration test
      if: github.ref == 'refs/heads/release'
      working-directory: ./backend/src
      run: npm test
    - name: Install FrontDepedencies
      working-directory: ./frontend/src
      run: npm install
    - name: Testes unitários front
      working-directory: ./frontend/src
      run: npm test