name: Node.js CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: ./backend/src
      run: npm install

    - name: Run test
      working-directory: ./backend/src
      run: npm test

    - name: Install FrontDepedencies
      working-directory: ./frontend/src
      run: npm install

    - name: Testes unitários front
      working-directory: ./frontend/src
      run: npm test

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: sqp_667b9da7edb3cf4de01151d6611a13bb75cf21b6
      with:
        args: >
        -Dsonar.projectKey=Unknown
        -Dsonar.sources=./backend/src,./frontend/src
        -Dsonar.host.url=https://f1ed-187-44-172-38.ngrok-free.app
        -Dsonar.login=sqp_667b9da7edb3cf4de01151d6611a13bb75cf21b6